services:
  db:
    image: postgres:16-alpine
    container_name: tg_bot.db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d botdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    container_name: tg_bot.migrations
    command: >
      sh -c "alembic upgrade head"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    container_name: tg_bot.bot
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
    - ./:/app

  redis:
    image: redis:latest
    container_name: tg_bot.redis
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: tg_bot.celery_worker
    command: python -m src.scripts.celery_worker
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./:/app

  celery_beat:
    build: .
    container_name: tg_bot.celery_beat
    command: python -m src.scripts.celery_beat
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./:/app

volumes:
  db_data: